version: "3"

services:
  db:
    image: "postgres:16.2-alpine3.19"
    environment:
      - POSTGRES_USER=nti
      - POSTGRES_PASSWORD=nti
      - POSTGRES_DB=nti
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres

  backend:
    build: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
  # mqtt:

  # grafana:

  influxdb:
    image: "influxdb:2.7.5-alpine"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=nti
      - DOCKER_INFLUXDB_INIT_PASSWORD=nti
      - DOCKER_INFLUXDB_INIT_ORG=cfeee1e5e4e00a
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    ports:
      - "8086:8086"
    volumes:
      - "influx_data:/var/lib/influxdb2"
      - "./.config/influx:/etc/influxdb2"

  telegraf:
    image: "telegraf:1.29.5"

# networks:

volumes:
  influx_data:
  postgres:
