FROM python:3.12-bookworm
WORKDIR /app

RUN apt-get update && apt-get install -y build-essential
RUN pip3 install poetry

COPY poetry.lock pyproject.toml ./
RUN poetry install --no-root --no-directory

COPY src ./src/
COPY .env ./.env

CMD ["poetry", "run", "--", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

EXPOSE 8000
