"""billing harringhton relations

Revision ID: 246bc52f8dfd
Revises: 1f9452717af6
Create Date: 2024-03-20 12:49:10.192598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246bc52f8dfd'
down_revision: Union[str, None] = '1f9452717af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bill', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill', type_='foreignkey')
    op.drop_column('bill', 'user_id')
    # ### end Alembic commands ###
